[variables]
NODE_ENV = "production"

[install]
installCommand = "npm ci --omit=dev"

[build]
builder = "heroku"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
