[build]
builder = "nixpacks"
buildCommand = "npm ci --omit=dev && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
