[variables]
NODE_ENV = "production"

[start]
cmd = "npm ci --omit=dev"

[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
